name: polity CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 23
    - name: Install dependencies
      run: yarn install --frozen-lockfile # the yarn.lock is updated according to the node version
    - name: Lint Code
      run: yarn format:check
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: stable
    - name: Run tests
      run: forge test -vvv
